#
# Module manifest for module 'NctApiClientLibrary'
#
# Generated by: Netwrix
#
# Generated on: 4/3/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'NctApiClientLibrary.psm1'
    
    # Version number of this module.
    ModuleVersion = '0.3.0'
    
    # Supported PSEditions
    CompatiblePSEditions = @('Core')
    
    # Author of this module
    Author = 'Netwrix'
    
    # Company or vendor of this module
    CompanyName = 'Netwrix'
    
    # Copyright statement for this module
    Copyright = '(c) 2025 Netwrix. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'Secure API client library for interacting with Netwrix Change Tracker Hub'
    
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.4' 
    
    # Required assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @(
        'System.Security.Cryptography.X509Certificates.dll'
        'System.Net.Http.dll'
    )
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Security', 'API', 'Netwrix', 'ChangeTracker')
            
            # A URL to the license for this module.
            LicenseUri = 'https://www.netwrix.com/eula.html'
            
            # A URL to the main website for this project.
            ProjectUri = 'https://www.netwrix.com/security_configuration_management_software.html'
            
            # ReleaseNotes of this module
            ReleaseNotes = 'Initial release with enhanced security features'
        }
    }
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Add-NctDatabaseCredential',
        'Add-NctProxiedDevice',
        'Get-NctAgents',
        'Get-NctCredentials',
        'Get-NctDevices',
        'New-NctApiCredential',
        'New-NctSession',
        'Protect-Credential',
        'Test-NctAuthenticationStatus',
        'Test-NctCertificate',
        'Remove-NctCredential',
        'Remove-NctProxiedDevice',
        'Test-NctSession',
        'Update-NctDevice'
    )
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()
    
    # Variables to export from this module
    VariablesToExport = @()
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()
}